stages:
  - verify
  - build
  - release-images

variables:
  GO_VERSION: "1.25"
  GOLANGCI_LINT_VERSION: "v2.11"

### VERIFY ####################################################################
compile:
  stage: verify
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
  image: golang:$GO_VERSION
  cache:
    key: go-mod-$CI_COMMIT_REF_SLUG
    paths:
      - .go-mod-cache/
  variables:
    GOMODCACHE: "$CI_PROJECT_DIR/.go-mod-cache"
  script:
    - go build ./...

lint:
  stage: verify
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
  image: golangci/golangci-lint:$GOLANGCI_LINT_VERSION-alpine
  cache:
    key: golangci-$CI_COMMIT_REF_SLUG
    paths:
      - .golangci-cache/
  variables:
    GOLANGCI_LINT_CACHE: "$CI_PROJECT_DIR/.golangci-cache"
  script:
    - go mod download
    - golangci-lint run

test:
  stage: verify
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
  image: golang:$GO_VERSION
  cache:
    key: go-mod-$CI_COMMIT_REF_SLUG
    paths:
      - .go-mod-cache/
  variables:
    GOMODCACHE: "$CI_PROJECT_DIR/.go-mod-cache"
  script:
    - go test ./...

alerts:
  stage: verify
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
  image:
    name: prom/prometheus:v2.53.0
    entrypoint: [""]
  script:
    - promtool check rules examples/monitoring/alerts.yaml


### BUILD IMAGE ###############################################################
build-image:
  stage: build
  image:
    name: registry.gitlab.com/flarenetwork/infra-public/pipeliner/kaniko-executor-stbl:v1.23.2-debug
    entrypoint: [""]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
  variables:
    DOCKERFILE: "Dockerfile"
    IMAGE: "tee-proxy"
  script:
    - >-
      args="--context ${CI_PROJECT_DIR}
        --dockerfile ${CI_PROJECT_DIR}/${DOCKERFILE}
        --build-arg REVISION=${CI_COMMIT_SHA}
        --registry-mirror mirror.gcr.io
        --compressed-caching=false
        --snapshot-mode=redo
        --no-push"
    - /kaniko/executor $args

    
.rules:release:
  rules:
    - if: $CI_COMMIT_TAG

#### RELEASE IMAGE #############################################################
release-images:auth:
  stage: release-images
  extends:
    - .rules:release
  image: registry.gitlab.com/flarenetwork/infra-public/pipeliner/pipeliner-stbl:v1.1.0
  id_tokens:
    OIDC_JOB_TOKEN:
      aud: https://gitlab.com
  variables:
    GCP_PROJECT: "flare-network-shared"
    GCP_PROJECT_NUMBER: "940168819002"
  before_script:
    - >-
      WORKLOAD_IDENTITY_POOL=$([ "$CI_COMMIT_REF_PROTECTED" == "true" ] &&
      echo "cr-oidc-gitlab-protected-pool" ||
      echo "cr-oidc-gitlab-pool")
    - >-
      WORKLOAD_IDENTITY_POOL_PROVIDER=$([ "$CI_COMMIT_REF_PROTECTED" == "true" ] &&
      echo "oidc-gitlab-protected" ||
      echo "oidc-gitlab-pool-provider")
    - >-
      SERVICE_ACCOUNT_EMAIL=$([ "$CI_COMMIT_REF_PROTECTED" == "true" ] &&
      echo "cr-prtctd-oidc-cntnr-img-bldr@flare-network-shared.iam.gserviceaccount.com" ||
      echo "cr-oidc-cntnr-img-bldr@flare-network-shared.iam.gserviceaccount.com")
    - . pipeliner gcloud-setup
  script:
    - echo "GOOGLE_OAUTH_ACCESS_TOKEN=$GOOGLE_OAUTH_ACCESS_TOKEN" > auth.env
  artifacts:
    reports:
      dotenv:
        - auth.env

release-images:
  stage: release-images
  extends:
    - .rules:release
  needs:
    - job: release-images:auth
      artifacts: true
  image:
    name: registry.gitlab.com/flarenetwork/infra-public/pipeliner/kaniko-executor-stbl:v1.23.2-debug
    entrypoint: [""]
  variables:
    DOCKERFILE: "Dockerfile"
    IMAGE: "tee-proxy"
  before_script:
    - mkdir -p /kaniko/.docker
    - auth_encoded=$(echo -n "oauth2accesstoken:$GOOGLE_OAUTH_ACCESS_TOKEN" | base64 | tr -d "\n")
    - echo "{\"auths\":{\"europe-west1-docker.pkg.dev\":{\"auth\":\"$auth_encoded\",\"email\":\"not@val.id\"}}}" > /kaniko/.docker/config.json
  script:
    - >-
      image_tag=$CI_COMMIT_TAG
    - echo "Will tag images with \`$image_tag\`."
    - >-
      args="--context ${CI_PROJECT_DIR}
        --dockerfile ${CI_PROJECT_DIR}/${DOCKERFILE}
        --build-arg REVISION=${CI_COMMIT_SHA}
        --build-arg VERSION=${CI_COMMIT_TAG}
        --cache=true
        --registry-mirror mirror.gcr.io
        --compressed-caching=false
        --destination europe-west1-docker.pkg.dev/flare-network-staging/containers/${IMAGE}:$image_tag"
    - >-
      if [[ $CI_COMMIT_REF_PROTECTED == "true" ]]; then
        args="$args --destination europe-west1-docker.pkg.dev/flare-network-production/containers/${IMAGE}:$image_tag"
      fi
    - /kaniko/executor $args
